### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by Lacan82** [aws/sagemaker-tensorflow-extensions#85]
I'm attempting to build from source, I do have libgtest-dev install Ubuntu 18.04, However, I am running into the following error.

 ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_cdrzn51/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_cdrzn51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o4dibvwo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/sagemaker-tensorflow
         cwd: /tmp/pip-req-build-_cdrzn51/
    Complete output (79 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.6
    creating build/lib.linux-aarch64-3.6/sagemaker_tensorflow
    copying src/sagemaker_tensorflow/__init__.py -> build/lib.linux-aarch64-3.6/sagemaker_tensorflow
    copying src/sagemaker_tensorflow/pipemode.py -> build/lib.linux-aarch64-3.6/sagemaker_tensorflow
    warning: build_py: byte-compiling is disabled, skipping.
    
    running build_ext
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working CXX compiler: /usr/bin/g++
    -- Check for working CXX compiler: /usr/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found CURL: -lcurl (found version "7.58.0")
    -- The C compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    python executable /usr/bin/python3
    2020-06-24 04:32:22.579549: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
    2020-06-24 04:32:26.986985: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    CMake Error at test/CMakeLists.txt:45 (target_compile_options):
      Cannot specify compile options for imported target "libgtest".
    
    
    2020-06-24 04:32:32.160340: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-_cdrzn51/build/temp.linux-aarch64-3.6/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-req-build-_cdrzn51/build/temp.linux-aarch64-3.6/CMakeFiles/CMakeError.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_cdrzn51/setup.py", line 122, in <module>
        'sagemaker', 'docker', 'boto3']
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-_cdrzn51/setup.py", line 66, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-_cdrzn51/setup.py", line 90, in build_extension
        cwd=self.build_temp, env=env)
      File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-_cdrzn51/src/pipemode_op', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-_cdrzn51/build/lib.linux-aarch64-3.6/sagemaker_tensorflow', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-_cdrzn51/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-_cdrzn51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-o4dibvwo/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/sagemaker-tensorflow Check the logs for full command output.

**Comment by ajaykarpur** [comment]
Which version of `g++` are you using? It's best to use the same `g++` version as the one used by TensorFlow.

**Comment by Lacan82** [comment]
The Docker Container I'm trying to build is using 7.5.0
